# auto generated by update_py.py

class TimeoutError(RuntimeError):
    pass
